package zian.example.pojo;

public class Deptartment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dep_id
     *
     * @mbggenerated Sat Feb 25 12:03:32 CST 2023
     */
    private Integer depId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dep_name
     *
     * @mbggenerated Sat Feb 25 12:03:32 CST 2023
     */
    private String depName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dep_id
     *
     * @return the value of department.dep_id
     *
     * @mbggenerated Sat Feb 25 12:03:32 CST 2023
     */
    public Integer getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.dep_id
     *
     * @param depId the value for department.dep_id
     *
     * @mbggenerated Sat Feb 25 12:03:32 CST 2023
     */
    public void setDepId(Integer depId) {
        this.depId = depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dep_name
     *
     * @return the value of department.dep_name
     *
     * @mbggenerated Sat Feb 25 12:03:32 CST 2023
     */
    public String getDepName() {
        return depName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.dep_name
     *
     * @param depName the value for department.dep_name
     *
     * @mbggenerated Sat Feb 25 12:03:32 CST 2023
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }
}