package zian.example.pojo;

public class Employee {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_id
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_name
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.age
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.gender
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.dep_id
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    private Integer depId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_id
     *
     * @return the value of employee.emp_id
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    public Employee(Integer empId, String empName, Integer age, String gender) {
        this.empId = empId;
        this.empName = empName;
        this.age = age;
        this.gender = gender;
    }

    /**
     * 构造函数
     * @return
     */

    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_id
     *
     * @param empId the value for employee.emp_id
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_name
     *
     * @return the value of employee.emp_name
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_name
     *
     * @param empName the value for employee.emp_name
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.age
     *
     * @return the value of employee.age
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.age
     *
     * @param age the value for employee.age
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.gender
     *
     * @return the value of employee.gender
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.gender
     *
     * @param gender the value for employee.gender
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.dep_id
     *
     * @return the value of employee.dep_id
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    public Integer getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.dep_id
     *
     * @param depId the value for employee.dep_id
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    public void setDepId(Integer depId) {
        this.depId = depId;
    }

    @Override
    public String toString() {
        return "Employee{" +
                "empId=" + empId +
                ", empName='" + empName + '\'' +
                ", age=" + age +
                ", gender='" + gender + '\'' +
                ", depId=" + depId +
                '}';
    }
}