package zian.example.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zian.example.pojo.Deptartment;
import zian.example.pojo.DeptartmentExample;

public interface DeptartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Sat Feb 25 12:03:32 CST 2023
     */
    int countByExample(DeptartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Sat Feb 25 12:03:32 CST 2023
     */
    int deleteByExample(DeptartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Sat Feb 25 12:03:32 CST 2023
     */
    int deleteByPrimaryKey(Integer depId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Sat Feb 25 12:03:32 CST 2023
     */
    int insert(Deptartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Sat Feb 25 12:03:32 CST 2023
     */
    int insertSelective(Deptartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Sat Feb 25 12:03:32 CST 2023
     */
    List<Deptartment> selectByExample(DeptartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Sat Feb 25 12:03:32 CST 2023
     */
    Deptartment selectByPrimaryKey(Integer depId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Sat Feb 25 12:03:32 CST 2023
     */
    int updateByExampleSelective(@Param("record") Deptartment record, @Param("example") DeptartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Sat Feb 25 12:03:32 CST 2023
     */
    int updateByExample(@Param("record") Deptartment record, @Param("example") DeptartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Sat Feb 25 12:03:32 CST 2023
     */
    int updateByPrimaryKeySelective(Deptartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbggenerated Sat Feb 25 12:03:32 CST 2023
     */
    int updateByPrimaryKey(Deptartment record);
}