package zian.example.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zian.example.pojo.Employee;
import zian.example.pojo.EmployeeExample;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     * ByExample: 通过条件
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    int countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *属性为null，也会赋值
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     * 选择性添加——属性为null，不会赋值
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    Employee selectByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Sat Feb 25 12:02:56 CST 2023
     */
    int updateByPrimaryKey(Employee record);
}